jobs:
  build:
    name: Build and test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: ${{ github.event_name == 'push' }}
      name: Checkout (with history)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - continue-on-error: true
      if: ${{ github.event_name != 'push' }}
      name: Checkout (without history)
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '17'
    - continue-on-error: true
      name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - continue-on-error: true
      name: Cache Gradle Home files
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gradle-home-examples-${{ hashFiles('**/*.gradle') }}
        path: ~/.gradle/caches
    - continue-on-error: true
      name: Build ConnectBot
      run: ./gradlew build bundleGoogleRelease
    - continue-on-error: true
      name: Run instrument tests
      uses: reactivecircus/android-emulator-runner@v2.30.1
      with:
        api-level: 28
        arch: x86_64
        profile: Nexus 4
        script: ./gradlew connectedCheck --continue
        target: default
    - continue-on-error: true
      if: ${{ github.event_name == 'push' }}
      name: Prepare release
      run: "if git describe --exact-match; then \\\n  TAGGED=yes\nfi\n\nif [[ -n $TAGGED\
        \ ]]; then\n  GITHUB_TAG=\"$(git describe)\"\n  echo \"${GITHUB_TAG}\" > tag.txt\n\
        \  echo \"Release ${GITHUB_TAG}\" > release-title.txt\nelse \\\n  GITHUB_TAG=\"\
        git-$(git describe)\"\n  GITHUB_TITLE=\"$(git log -1 --pretty=%B | head -1)\"\
        \n  echo \"${GITHUB_TAG}\" > tag.txt\n  echo \"${GITHUB_TAG}: ${GITHUB_TITLE}\"\
        \ > release-title.txt\nfi\ncp ./app/build/outputs/apk/oss/release/app-oss-release-unsigned.apk\
        \ ConnectBot-${GITHUB_TAG}-oss-unsigned.apk\ncp ./app/build/outputs/apk/google/release/app-google-release-unsigned.apk\
        \ ConnectBot-${GITHUB_TAG}-google-unsigned.apk\ncp ./app/build/outputs/bundle/googleRelease/app-google-release.aab\
        \ ConnectBot-${GITHUB_TAG}-google-unsigned.aab\ncp ./app/build/outputs/native-debug-symbols/googleRelease/native-debug-symbols.zip\
        \ ConnectBot-${GITHUB_TAG}-google.native-debug-symbols.zip\ncp ./app/build/outputs/native-debug-symbols/ossRelease/native-debug-symbols.zip\
        \ ConnectBot-${GITHUB_TAG}-oss.native-debug-symbols.zip\n"
    - continue-on-error: true
      if: ${{ github.event_name == 'push' }}
      name: Store artifacts for upload
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: 'release-title.txt

          tag.txt

          ConnectBot-*-unsigned.apk

          ConnectBot-*-unsigned.aab

          ConnectBot-*.native-debug-symbols.zip

          '
  signing:
    if: ${{ (github.event_name == 'push') && (github.repository == 'connectbot/connectbot')
      && ((github.ref == 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v'))
      }}
    name: Trigger remote signing
    needs: upload
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download artifacts from previous job
      uses: actions/download-artifact@v4
      with:
        name: apk
    - continue-on-error: true
      id: name
      name: Set release name
      run: 'echo "GITHUB_TAG=$(cat tag.txt)" >> "$GITHUB_OUTPUT"

        '
    - continue-on-error: true
      name: Call remote signer
      uses: distributhor/workflow-webhook@v3.0.7
      with:
        data: '{"tag_id": "${{ steps.name.outputs.GITHUB_TAG }}"}'
        webhook_url: ${{ secrets.SIGNER_WEBHOOK_URL }}
  upload:
    if: ${{ (github.event_name == 'push') && (github.repository == 'connectbot/connectbot')
      && ((github.ref == 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v'))
      }}
    name: Upload to GitHub releases
    needs: build
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download artifacts from previous job
      uses: actions/download-artifact@v4
      with:
        name: apk
    - continue-on-error: true
      id: name
      name: Set release name
      run: 'echo "RELEASE_TITLE=$(cat release-title.txt)" >> "$GITHUB_OUTPUT"

        echo "GITHUB_TAG=$(cat tag.txt)" >> "$GITHUB_OUTPUT"

        '
    - continue-on-error: true
      name: Upload release
      uses: softprops/action-gh-release@v2
      with:
        body: Untested build
        draft: true
        files: 'ConnectBot-*-unsigned.apk

          ConnectBot-*-unsigned.aab

          ConnectBot-*.native-debug-symbols.zip

          '
        generate_release_notes: true
        name: ${{ steps.name.outputs.RELEASE_TITLE }}
        tag_name: ${{ steps.name.outputs.GITHUB_TAG }}
name: Continuous Integration
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
