jobs:
  copy:
    name: Copy to po-files
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        BRANCH: po-files
        FOLDER: app/locale
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE: 'Automated export to {target-branch}


          From branch main commit {long-sha}:


          {msg}'
        REPO: self
        SKIP_EMPTY_COMMITS: true
      name: Push subdirectory
      uses: s0/git-publish-subdir-action@develop
name: Copy .po files to po-files branch
on:
  repository_dispatch:
    types: trigger-ga___export-po-files.yml
