jobs:
  import:
    env:
      BAZAAR_URI: lp:~kennyr/connectbot/po-output
      PO_SUBDIR: app/locale
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Install bazaar
      run: "sudo apt-get update && \\\nsudo apt-get install -y --no-install-recommends\
        \ \\\n    bzr \\\n    ca-certificates \\\n    rsync\n"
    - continue-on-error: true
      name: Branch Bazaar translation exports
      run: 'cd ${{ runner.temp }}

        bzr branch lp:~kennyr/connectbot/po-output

        cd po-output

        echo "REVNO=$(bzr revno)" >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Copy exported translations to workspace
      run: "rsync -av --exclude .bzr --exclude '**/oc.po' --exclude '**/ca@valencia.po'\
        \ \\\n    \"${{ runner.temp }}/${BAZAAR_URI##*/}/\" \"${GITHUB_WORKSPACE}/${PO_SUBDIR}/\"\
        \necho $REVNO > \"${GITHUB_WORKSPACE}/${PO_SUBDIR}/.revno\"\n"
    - continue-on-error: true
      name: Try importing the translations
      run: 'TRANSLATIONS_ONLY=1 ./gradlew :translations:importToAndroid

        '
    - continue-on-error: true
      name: Create pull request
      uses: peter-evans/create-pull-request@v6
      with:
        assignees: kruton
        author: Translations Bot <no-reply+translations@connectbot.org>
        body: 'Automated import of translations from Launchpad.

          '
        branch: translations/import
        commit-message: 'Automated translations import


          Translations imported from Launchpad.

          '
        labels: translations, automated pr
        reviewers: kruton
        title: '[Translations] Automatic update'
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Report pull request creation
      run: echo "Created pull request number ${{ env.PULL_REQUEST_NUMBER }}"
name: Translations import
on:
  repository_dispatch:
    types: trigger-ga___translations-import.yml
